apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-details-app
  name: my-details-app
spec:
  containers:
  - image: details-app
    name: my-details-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
