apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-reviews-app
  name: my-reviews-app
spec:
  containers:
  - env:
    - name: RATINGS_HOSTNAME
      value: 172.17.0.8
    - name: RATINGS_PORT
      value: "9080"
    image: istio/examples-bookinfo-reviews-v2
    name: my-reviews-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
