apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-details-app
  labels:
    run: my-details-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-details-app
  template:
    metadata:
      labels:
        app: my-details-app
    spec:
      containers:
      - name: my-details-app
        image: istio/examples-bookinfo-details-v2
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always