apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-productpage-app
  namespace: dev
  labels:
    run: my-productpage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-productpage-app
  template:
    metadata:
      labels:
        app: my-productpage-app
    spec:
      containers:
      - name: my-productpage-app
        image: istio/examples-bookinfo-productpage-v1
        resources: {}
        envFrom:
        - configMapRef:
            name: productpage-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always