apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ratings-app
  labels:
    run: my-ratings-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ratings-app
  template:
    metadata:
      labels:
        app: my-ratings-app
    spec:
      containers:
      - name: my-ratings-app
        image: istio/examples-bookinfo-ratings-v1
        resources: {}
        env:
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rating-secret
              key: MYSQL_DB_PASSWORD
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: rating-secret
              key: MYSQL_DB_USER
        envFrom:
        - configMapRef:
            name: ratings-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always