apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-reviews-app
  labels:
    run: my-reviews-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-reviews-app
  template:
    metadata:
      labels:
        app: my-reviews-app
    spec:
      containers:
      - name: my-reviews-app
        image: istio/examples-bookinfo-reviews-v3
        resources: {}
        env:
        - name: RATINGS_HOSTNAME
          value: ratings-svc
        - name: RATINGS_PORT
          value: "9080"
      dnsPolicy: ClusterFirst
      restartPolicy: Always