apiVersion: batch/v1
kind: CronJob
metadata:
  name: mi-cronjob
  namespace: dev
spec:
  schedule: "* * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-app
            image: curlimages/curl:7.72.0
            command: 
            - /bin/sh
            - -c
            # - date; echo Hello from the Kubernetes cluster
            - "curl http://reviews-svc/health"
          restartPolicy: OnFailure