apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-productpage-app
  labels:
    run: my-productpage-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-productpage-app
  template:
    metadata:
      labels:
        app: my-productpage-app
    spec:
      containers:
      - name: my-productpage-app
        image: istio/examples-bookinfo-productpage-v1
        resources: {}
        env:
        - name: REVIEWS_HOSTNAME
          value: 172.17.0.2
        - name: DETAILS_HOSTNAME
          value: 172.17.0.4
        - name: RATINGS_HOSTNAME
          value: 172.17.0.8
      dnsPolicy: ClusterFirst
      restartPolicy: Always