apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ratings-app
  labels:
    run: my-ratings-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ratings-app
  template:
    metadata:
      labels:
        app: my-ratings-app
    spec:
      containers:
      - image: istio/examples-bookinfo-ratings-v1
        name: my-ratings-app
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always