apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-ratings-app
  name: my-ratings-app
spec:
  containers:
  - image: ratings-app
    name: my-ratings-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
